
import Link from 'next/link';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav>
        <ul>
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/books">Books</Link>
        </li>
        <li>
          <Link href="/authors">Authors</Link>
        </li>
        </ul>
        </nav>
      </header>
      {children}
      </body>

    </html>
    
  )
}
